image: thrillworks/node-build
cache:
  paths:
    - node_modules
stages:
  - deploy
pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm run storybook:build
    - mv storybook-static public/_storybook
  artifacts:
    paths:
      - public
  only:
    - master
